- name: "bedwars"
  displayName: "BedWars"
  aliases:
    - "bw"
    - "team_bedwars"
    - "Team BedWars"
  active: true
  scoreType: "wins"
  shouldTrack: true
  hasPreLobby: true
  icon: "https://forums.cubecraftcdn.com/xenforo/data/avatars/o/307/307406.jpg?1591095808"
  gameFlags:
    - "RespawnTags"
    - "DiscordRpcPlayerTracking"
    - "HasRespawns"
    - "MiniGame"

- name: "disasters"
  displayName: "Disasters"
  aliases:
    - "disaster"
  active: true
  scoreType: "wins"
  shouldTrack: true
  hasPreLobby: false
  icon: "https://forums.cubecraftcdn.com/xenforo/data/avatars/o/307/307406.jpg?1591095808"
  gameFlags:
    - "DiscordRpcPlayerTracking"
    - "MiniGame"

- name: "ender"
  displayName: "Ender"
  aliases: []
  active: false
  scoreType: "wins"
  shouldTrack: false
  hasPreLobby: false
  icon: "https://forums.cubecraftcdn.com/xenforo/data/avatars/o/307/307406.jpg?1591095808"
  gameFlags:
    - "DiscordRpcPlayerTracking"
    - "MiniGame"

- name: "free_for_all"
  displayName: "Free For All"
  aliases:
    - "ffa"
  active: true
  scoreType: "kills"
  shouldTrack: true
  hasPreLobby: false
  icon: "https://forums.cubecraftcdn.com/xenforo/serve/styles/cubecraft/cubecraft/minigames/node-icons/pvp.png"
  gameFlags:
    - "HasRespawns"
    - "AlternateMapTracker"
    - "NoPreGameState"

- name: "main_lobby"
  displayName: "Main Lobby"
  aliases: []
  active: false
  scoreType: ""
  shouldTrack: false
  hasPreLobby: false
  icon: "https://forums.cubecraftcdn.com/xenforo/data/avatars/o/307/307406.jpg?1591095808"
  gameFlags:
    - "Lobby"
    - "NoPreGameState"

- name: "parkour"
  displayName: "Parkour"
  aliases:
    - "Simple Parkour"
    - "Easy Parkour"
    - "Medium Parkour"
    - "Hard Parkour"
  active: true
  scoreType: "medals"
  shouldTrack: false
  hasPreLobby: false
  icon: "https://forums.cubecraftcdn.com/xenforo/serve/styles/cubecraft/cubecraft/minigames/node-icons/parkour.png"
  gameFlags:
    - "IgnoreScoreboardUpdates"
    - "NoPreGameState"
    - "HasRespawns"

- name: "pillars_of_fortune"
  displayName: "Pillars of Fortune"
  aliases:
    - "pof"
    - "ic"
    - "pf"
  active: true
  scoreType: "wins"
  shouldTrack: true
  hasPreLobby: false
  icon: "https://forums.cubecraftcdn.com/xenforo/data/avatars/o/307/307406.jpg?1591095808"
  gameFlags:
    - "DiscordRpcPlayerTracking"
    - "MiniGame"

- name: "lucky_pillars"
  displayName: "Lucky Pillars"
  aliases:
    - "lp"
  active: true
  scoreType: "wins"
  shouldTrack: true
  hasPreLobby: false
  icon: "https://forums.cubecraftcdn.com/xenforo/serve/styles/cubecraft/cubecraft/minigames/node-icons/lucky-islands.png"
  gameFlags:
    - "DiscordRpcPlayerTracking"
    - "MiniGame"

- name: "skyblock"
  displayName: "Skyblock"
  aliases:
    - "sb"
  active: false
  scoreType: ""
  shouldTrack: false
  hasPreLobby: false
  icon: "https://forums.cubecraftcdn.com/xenforo/serve/styles/cubecraft/cubecraft/minigames/node-icons/skyblock.png"
  gameFlags:
    - "DontDropTools"
    - "NoPreGameState"
    - "HasRespawns"

- name: "snowman_survival"
  displayName: "Snowman Survival"
  aliases:
    - "ss"
  active: false
  scoreType: "medals"
  shouldTrack: true
  hasPreLobby: false
  icon: "https://forums.cubecraftcdn.com/xenforo/data/avatars/o/307/307406.jpg?1591095808"
  gameFlags:
    - "DiscordRpcPlayerTracking"
    - "MiniGame"
    - "InGameAfterElimination"
    - "HasRespawns"

- name: "solo_lucky_islands"
  displayName: "Lucky Islands"
  aliases:
    - "sli"
    - "li"
    - "lucky_islands"
    - "solo_luckyislands"
  active: true
  scoreType: "wins"
  shouldTrack: true
  hasPreLobby: false
  icon: "https://forums.cubecraftcdn.com/xenforo/serve/styles/cubecraft/cubecraft/minigames/node-icons/lucky-islands.png"
  gameFlags:
    - "DiscordRpcPlayerTracking"
    - "MiniGame"

- name: "solo_skywars"
  displayName: "Solo SkyWars"
  aliases:
    - "sw"
    - "skywars"
  active: true
  scoreType: "wins"
  shouldTrack: true
  hasPreLobby: false
  icon: "https://forums.cubecraftcdn.com/xenforo/serve/styles/cubecraft/cubecraft/minigames/node-icons/skywars.png"
  gameFlags:
    - "DiscordRpcPlayerTracking"
    - "MiniGame"

- name: "team_eggwars"
  displayName: "Team EggWars"
  aliases:
    - "tew"
    - "ew"
    - "eggwars"
  active: true
  scoreType: "wins"
  shouldTrack: true
  hasPreLobby: true
  icon: "https://forums.cubecraftcdn.com/xenforo/serve/styles/cubecraft/cubecraft/minigames/node-icons/eggwars.png"
  gameFlags:
    - "DiscordRpcPlayerTracking"
    - "HasRespawns"
    - "Cooldowns"
    - "RespawnTags"
    - "MiniGame"

- name: "team_lucky_islands"
  displayName: "Team Lucky Islands"
  aliases:
    - "tli"
  active: false
  scoreType: "wins"
  shouldTrack: true
  hasPreLobby: false
  icon: "https://forums.cubecraftcdn.com/xenforo/serve/styles/cubecraft/cubecraft/minigames/node-icons/lucky-islands.png"
  gameFlags:
    - "DiscordRpcPlayerTracking"
    - "MiniGame"

- name: "mob_who"
  displayName: "Mob Who"
  aliases:
    - "mw"
  active: true
  scoreType: "wins"
  shouldTrack: false
  hasPreLobby: false
  icon: "https://forums.cubecraftcdn.com/xenforo/data/avatars/o/307/307406.jpg?1591095808"
  gameFlags:
    - "DiscordRpcPlayerTracking"
    - "IgnoreScoreboardUpdates"
    - "MiniGame"
