// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.2
package art.ameliah.laby.addons.cubepanion.core.proto;

public interface C2SDisconnectPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.laby.addons.cubepanion.C2SDisconnectPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reason = 1;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 1;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
