// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.3
package art.ameliah.laby.addons.cubepanion.core.proto;

/**
 * Protobuf type {@code art.ameliah.laby.addons.cubepanion.C2SPacket}
 */
public final class C2SPacket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:art.ameliah.laby.addons.cubepanion.C2SPacket)
    C2SPacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use C2SPacket.newBuilder() to construct.
  private C2SPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private C2SPacket() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new C2SPacket();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return art.ameliah.laby.addons.cubepanion.core.proto.Packets.internal_static_art_ameliah_laby_addons_cubepanion_C2SPacket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return art.ameliah.laby.addons.cubepanion.core.proto.Packets.internal_static_art_ameliah_laby_addons_cubepanion_C2SPacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket.class, art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket.Builder.class);
  }

  private int packetCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object packet_;
  public enum PacketCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    UPDATELOCATION(1),
    UPDATEPERK(2),
    DISCONNECT(4),
    PING(5),
    PACKET_NOT_SET(0);
    private final int value;
    private PacketCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PacketCase valueOf(int value) {
      return forNumber(value);
    }

    public static PacketCase forNumber(int value) {
      switch (value) {
        case 1: return UPDATELOCATION;
        case 2: return UPDATEPERK;
        case 4: return DISCONNECT;
        case 5: return PING;
        case 0: return PACKET_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PacketCase
  getPacketCase() {
    return PacketCase.forNumber(
        packetCase_);
  }

  public static final int UPDATELOCATION_FIELD_NUMBER = 1;
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.C2SUpdateLocationPacket updateLocation = 1;</code>
   * @return Whether the updateLocation field is set.
   */
  @java.lang.Override
  public boolean hasUpdateLocation() {
    return packetCase_ == 1;
  }
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.C2SUpdateLocationPacket updateLocation = 1;</code>
   * @return The updateLocation.
   */
  @java.lang.Override
  public art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket getUpdateLocation() {
    if (packetCase_ == 1) {
       return (art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket) packet_;
    }
    return art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket.getDefaultInstance();
  }
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.C2SUpdateLocationPacket updateLocation = 1;</code>
   */
  @java.lang.Override
  public art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacketOrBuilder getUpdateLocationOrBuilder() {
    if (packetCase_ == 1) {
       return (art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket) packet_;
    }
    return art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket.getDefaultInstance();
  }

  public static final int UPDATEPERK_FIELD_NUMBER = 2;
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.C2SPerkUpdatePacket updatePerk = 2;</code>
   * @return Whether the updatePerk field is set.
   */
  @java.lang.Override
  public boolean hasUpdatePerk() {
    return packetCase_ == 2;
  }
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.C2SPerkUpdatePacket updatePerk = 2;</code>
   * @return The updatePerk.
   */
  @java.lang.Override
  public art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket getUpdatePerk() {
    if (packetCase_ == 2) {
       return (art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket) packet_;
    }
    return art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket.getDefaultInstance();
  }
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.C2SPerkUpdatePacket updatePerk = 2;</code>
   */
  @java.lang.Override
  public art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacketOrBuilder getUpdatePerkOrBuilder() {
    if (packetCase_ == 2) {
       return (art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket) packet_;
    }
    return art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket.getDefaultInstance();
  }

  public static final int DISCONNECT_FIELD_NUMBER = 4;
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.C2SDisconnectPacket disconnect = 4;</code>
   * @return Whether the disconnect field is set.
   */
  @java.lang.Override
  public boolean hasDisconnect() {
    return packetCase_ == 4;
  }
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.C2SDisconnectPacket disconnect = 4;</code>
   * @return The disconnect.
   */
  @java.lang.Override
  public art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket getDisconnect() {
    if (packetCase_ == 4) {
       return (art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket) packet_;
    }
    return art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket.getDefaultInstance();
  }
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.C2SDisconnectPacket disconnect = 4;</code>
   */
  @java.lang.Override
  public art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacketOrBuilder getDisconnectOrBuilder() {
    if (packetCase_ == 4) {
       return (art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket) packet_;
    }
    return art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket.getDefaultInstance();
  }

  public static final int PING_FIELD_NUMBER = 5;
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.C2SPingPacket ping = 5;</code>
   * @return Whether the ping field is set.
   */
  @java.lang.Override
  public boolean hasPing() {
    return packetCase_ == 5;
  }
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.C2SPingPacket ping = 5;</code>
   * @return The ping.
   */
  @java.lang.Override
  public art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket getPing() {
    if (packetCase_ == 5) {
       return (art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket) packet_;
    }
    return art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket.getDefaultInstance();
  }
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.C2SPingPacket ping = 5;</code>
   */
  @java.lang.Override
  public art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacketOrBuilder getPingOrBuilder() {
    if (packetCase_ == 5) {
       return (art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket) packet_;
    }
    return art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (packetCase_ == 1) {
      output.writeMessage(1, (art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket) packet_);
    }
    if (packetCase_ == 2) {
      output.writeMessage(2, (art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket) packet_);
    }
    if (packetCase_ == 4) {
      output.writeMessage(4, (art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket) packet_);
    }
    if (packetCase_ == 5) {
      output.writeMessage(5, (art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket) packet_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (packetCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket) packet_);
    }
    if (packetCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket) packet_);
    }
    if (packetCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket) packet_);
    }
    if (packetCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket) packet_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket)) {
      return super.equals(obj);
    }
    art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket other = (art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket) obj;

    if (!getPacketCase().equals(other.getPacketCase())) return false;
    switch (packetCase_) {
      case 1:
        if (!getUpdateLocation()
            .equals(other.getUpdateLocation())) return false;
        break;
      case 2:
        if (!getUpdatePerk()
            .equals(other.getUpdatePerk())) return false;
        break;
      case 4:
        if (!getDisconnect()
            .equals(other.getDisconnect())) return false;
        break;
      case 5:
        if (!getPing()
            .equals(other.getPing())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (packetCase_) {
      case 1:
        hash = (37 * hash) + UPDATELOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getUpdateLocation().hashCode();
        break;
      case 2:
        hash = (37 * hash) + UPDATEPERK_FIELD_NUMBER;
        hash = (53 * hash) + getUpdatePerk().hashCode();
        break;
      case 4:
        hash = (37 * hash) + DISCONNECT_FIELD_NUMBER;
        hash = (53 * hash) + getDisconnect().hashCode();
        break;
      case 5:
        hash = (37 * hash) + PING_FIELD_NUMBER;
        hash = (53 * hash) + getPing().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code art.ameliah.laby.addons.cubepanion.C2SPacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:art.ameliah.laby.addons.cubepanion.C2SPacket)
      art.ameliah.laby.addons.cubepanion.core.proto.C2SPacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return art.ameliah.laby.addons.cubepanion.core.proto.Packets.internal_static_art_ameliah_laby_addons_cubepanion_C2SPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return art.ameliah.laby.addons.cubepanion.core.proto.Packets.internal_static_art_ameliah_laby_addons_cubepanion_C2SPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket.class, art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket.Builder.class);
    }

    // Construct using art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (updateLocationBuilder_ != null) {
        updateLocationBuilder_.clear();
      }
      if (updatePerkBuilder_ != null) {
        updatePerkBuilder_.clear();
      }
      if (disconnectBuilder_ != null) {
        disconnectBuilder_.clear();
      }
      if (pingBuilder_ != null) {
        pingBuilder_.clear();
      }
      packetCase_ = 0;
      packet_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return art.ameliah.laby.addons.cubepanion.core.proto.Packets.internal_static_art_ameliah_laby_addons_cubepanion_C2SPacket_descriptor;
    }

    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket getDefaultInstanceForType() {
      return art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket.getDefaultInstance();
    }

    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket build() {
      art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket buildPartial() {
      art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket result = new art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket result) {
      result.packetCase_ = packetCase_;
      result.packet_ = this.packet_;
      if (packetCase_ == 1 &&
          updateLocationBuilder_ != null) {
        result.packet_ = updateLocationBuilder_.build();
      }
      if (packetCase_ == 2 &&
          updatePerkBuilder_ != null) {
        result.packet_ = updatePerkBuilder_.build();
      }
      if (packetCase_ == 4 &&
          disconnectBuilder_ != null) {
        result.packet_ = disconnectBuilder_.build();
      }
      if (packetCase_ == 5 &&
          pingBuilder_ != null) {
        result.packet_ = pingBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket) {
        return mergeFrom((art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket other) {
      if (other == art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket.getDefaultInstance()) return this;
      switch (other.getPacketCase()) {
        case UPDATELOCATION: {
          mergeUpdateLocation(other.getUpdateLocation());
          break;
        }
        case UPDATEPERK: {
          mergeUpdatePerk(other.getUpdatePerk());
          break;
        }
        case DISCONNECT: {
          mergeDisconnect(other.getDisconnect());
          break;
        }
        case PING: {
          mergePing(other.getPing());
          break;
        }
        case PACKET_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getUpdateLocationFieldBuilder().getBuilder(),
                  extensionRegistry);
              packetCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getUpdatePerkFieldBuilder().getBuilder(),
                  extensionRegistry);
              packetCase_ = 2;
              break;
            } // case 18
            case 34: {
              input.readMessage(
                  getDisconnectFieldBuilder().getBuilder(),
                  extensionRegistry);
              packetCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getPingFieldBuilder().getBuilder(),
                  extensionRegistry);
              packetCase_ = 5;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int packetCase_ = 0;
    private java.lang.Object packet_;
    public PacketCase
        getPacketCase() {
      return PacketCase.forNumber(
          packetCase_);
    }

    public Builder clearPacket() {
      packetCase_ = 0;
      packet_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket, art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacketOrBuilder> updateLocationBuilder_;
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SUpdateLocationPacket updateLocation = 1;</code>
     * @return Whether the updateLocation field is set.
     */
    @java.lang.Override
    public boolean hasUpdateLocation() {
      return packetCase_ == 1;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SUpdateLocationPacket updateLocation = 1;</code>
     * @return The updateLocation.
     */
    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket getUpdateLocation() {
      if (updateLocationBuilder_ == null) {
        if (packetCase_ == 1) {
          return (art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket) packet_;
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket.getDefaultInstance();
      } else {
        if (packetCase_ == 1) {
          return updateLocationBuilder_.getMessage();
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SUpdateLocationPacket updateLocation = 1;</code>
     */
    public Builder setUpdateLocation(art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket value) {
      if (updateLocationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packet_ = value;
        onChanged();
      } else {
        updateLocationBuilder_.setMessage(value);
      }
      packetCase_ = 1;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SUpdateLocationPacket updateLocation = 1;</code>
     */
    public Builder setUpdateLocation(
        art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket.Builder builderForValue) {
      if (updateLocationBuilder_ == null) {
        packet_ = builderForValue.build();
        onChanged();
      } else {
        updateLocationBuilder_.setMessage(builderForValue.build());
      }
      packetCase_ = 1;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SUpdateLocationPacket updateLocation = 1;</code>
     */
    public Builder mergeUpdateLocation(art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket value) {
      if (updateLocationBuilder_ == null) {
        if (packetCase_ == 1 &&
            packet_ != art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket.getDefaultInstance()) {
          packet_ = art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket.newBuilder((art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket) packet_)
              .mergeFrom(value).buildPartial();
        } else {
          packet_ = value;
        }
        onChanged();
      } else {
        if (packetCase_ == 1) {
          updateLocationBuilder_.mergeFrom(value);
        } else {
          updateLocationBuilder_.setMessage(value);
        }
      }
      packetCase_ = 1;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SUpdateLocationPacket updateLocation = 1;</code>
     */
    public Builder clearUpdateLocation() {
      if (updateLocationBuilder_ == null) {
        if (packetCase_ == 1) {
          packetCase_ = 0;
          packet_ = null;
          onChanged();
        }
      } else {
        if (packetCase_ == 1) {
          packetCase_ = 0;
          packet_ = null;
        }
        updateLocationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SUpdateLocationPacket updateLocation = 1;</code>
     */
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket.Builder getUpdateLocationBuilder() {
      return getUpdateLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SUpdateLocationPacket updateLocation = 1;</code>
     */
    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacketOrBuilder getUpdateLocationOrBuilder() {
      if ((packetCase_ == 1) && (updateLocationBuilder_ != null)) {
        return updateLocationBuilder_.getMessageOrBuilder();
      } else {
        if (packetCase_ == 1) {
          return (art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket) packet_;
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SUpdateLocationPacket updateLocation = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket, art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacketOrBuilder> 
        getUpdateLocationFieldBuilder() {
      if (updateLocationBuilder_ == null) {
        if (!(packetCase_ == 1)) {
          packet_ = art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket.getDefaultInstance();
        }
        updateLocationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket, art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacketOrBuilder>(
                (art.ameliah.laby.addons.cubepanion.core.proto.C2SUpdateLocationPacket) packet_,
                getParentForChildren(),
                isClean());
        packet_ = null;
      }
      packetCase_ = 1;
      onChanged();
      return updateLocationBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket, art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacketOrBuilder> updatePerkBuilder_;
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPerkUpdatePacket updatePerk = 2;</code>
     * @return Whether the updatePerk field is set.
     */
    @java.lang.Override
    public boolean hasUpdatePerk() {
      return packetCase_ == 2;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPerkUpdatePacket updatePerk = 2;</code>
     * @return The updatePerk.
     */
    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket getUpdatePerk() {
      if (updatePerkBuilder_ == null) {
        if (packetCase_ == 2) {
          return (art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket) packet_;
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket.getDefaultInstance();
      } else {
        if (packetCase_ == 2) {
          return updatePerkBuilder_.getMessage();
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPerkUpdatePacket updatePerk = 2;</code>
     */
    public Builder setUpdatePerk(art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket value) {
      if (updatePerkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packet_ = value;
        onChanged();
      } else {
        updatePerkBuilder_.setMessage(value);
      }
      packetCase_ = 2;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPerkUpdatePacket updatePerk = 2;</code>
     */
    public Builder setUpdatePerk(
        art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket.Builder builderForValue) {
      if (updatePerkBuilder_ == null) {
        packet_ = builderForValue.build();
        onChanged();
      } else {
        updatePerkBuilder_.setMessage(builderForValue.build());
      }
      packetCase_ = 2;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPerkUpdatePacket updatePerk = 2;</code>
     */
    public Builder mergeUpdatePerk(art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket value) {
      if (updatePerkBuilder_ == null) {
        if (packetCase_ == 2 &&
            packet_ != art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket.getDefaultInstance()) {
          packet_ = art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket.newBuilder((art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket) packet_)
              .mergeFrom(value).buildPartial();
        } else {
          packet_ = value;
        }
        onChanged();
      } else {
        if (packetCase_ == 2) {
          updatePerkBuilder_.mergeFrom(value);
        } else {
          updatePerkBuilder_.setMessage(value);
        }
      }
      packetCase_ = 2;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPerkUpdatePacket updatePerk = 2;</code>
     */
    public Builder clearUpdatePerk() {
      if (updatePerkBuilder_ == null) {
        if (packetCase_ == 2) {
          packetCase_ = 0;
          packet_ = null;
          onChanged();
        }
      } else {
        if (packetCase_ == 2) {
          packetCase_ = 0;
          packet_ = null;
        }
        updatePerkBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPerkUpdatePacket updatePerk = 2;</code>
     */
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket.Builder getUpdatePerkBuilder() {
      return getUpdatePerkFieldBuilder().getBuilder();
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPerkUpdatePacket updatePerk = 2;</code>
     */
    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacketOrBuilder getUpdatePerkOrBuilder() {
      if ((packetCase_ == 2) && (updatePerkBuilder_ != null)) {
        return updatePerkBuilder_.getMessageOrBuilder();
      } else {
        if (packetCase_ == 2) {
          return (art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket) packet_;
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPerkUpdatePacket updatePerk = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket, art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacketOrBuilder> 
        getUpdatePerkFieldBuilder() {
      if (updatePerkBuilder_ == null) {
        if (!(packetCase_ == 2)) {
          packet_ = art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket.getDefaultInstance();
        }
        updatePerkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket, art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacketOrBuilder>(
                (art.ameliah.laby.addons.cubepanion.core.proto.C2SPerkUpdatePacket) packet_,
                getParentForChildren(),
                isClean());
        packet_ = null;
      }
      packetCase_ = 2;
      onChanged();
      return updatePerkBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket, art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacketOrBuilder> disconnectBuilder_;
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SDisconnectPacket disconnect = 4;</code>
     * @return Whether the disconnect field is set.
     */
    @java.lang.Override
    public boolean hasDisconnect() {
      return packetCase_ == 4;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SDisconnectPacket disconnect = 4;</code>
     * @return The disconnect.
     */
    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket getDisconnect() {
      if (disconnectBuilder_ == null) {
        if (packetCase_ == 4) {
          return (art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket) packet_;
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket.getDefaultInstance();
      } else {
        if (packetCase_ == 4) {
          return disconnectBuilder_.getMessage();
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SDisconnectPacket disconnect = 4;</code>
     */
    public Builder setDisconnect(art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket value) {
      if (disconnectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packet_ = value;
        onChanged();
      } else {
        disconnectBuilder_.setMessage(value);
      }
      packetCase_ = 4;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SDisconnectPacket disconnect = 4;</code>
     */
    public Builder setDisconnect(
        art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket.Builder builderForValue) {
      if (disconnectBuilder_ == null) {
        packet_ = builderForValue.build();
        onChanged();
      } else {
        disconnectBuilder_.setMessage(builderForValue.build());
      }
      packetCase_ = 4;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SDisconnectPacket disconnect = 4;</code>
     */
    public Builder mergeDisconnect(art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket value) {
      if (disconnectBuilder_ == null) {
        if (packetCase_ == 4 &&
            packet_ != art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket.getDefaultInstance()) {
          packet_ = art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket.newBuilder((art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket) packet_)
              .mergeFrom(value).buildPartial();
        } else {
          packet_ = value;
        }
        onChanged();
      } else {
        if (packetCase_ == 4) {
          disconnectBuilder_.mergeFrom(value);
        } else {
          disconnectBuilder_.setMessage(value);
        }
      }
      packetCase_ = 4;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SDisconnectPacket disconnect = 4;</code>
     */
    public Builder clearDisconnect() {
      if (disconnectBuilder_ == null) {
        if (packetCase_ == 4) {
          packetCase_ = 0;
          packet_ = null;
          onChanged();
        }
      } else {
        if (packetCase_ == 4) {
          packetCase_ = 0;
          packet_ = null;
        }
        disconnectBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SDisconnectPacket disconnect = 4;</code>
     */
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket.Builder getDisconnectBuilder() {
      return getDisconnectFieldBuilder().getBuilder();
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SDisconnectPacket disconnect = 4;</code>
     */
    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacketOrBuilder getDisconnectOrBuilder() {
      if ((packetCase_ == 4) && (disconnectBuilder_ != null)) {
        return disconnectBuilder_.getMessageOrBuilder();
      } else {
        if (packetCase_ == 4) {
          return (art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket) packet_;
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SDisconnectPacket disconnect = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket, art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacketOrBuilder> 
        getDisconnectFieldBuilder() {
      if (disconnectBuilder_ == null) {
        if (!(packetCase_ == 4)) {
          packet_ = art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket.getDefaultInstance();
        }
        disconnectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket, art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacketOrBuilder>(
                (art.ameliah.laby.addons.cubepanion.core.proto.C2SDisconnectPacket) packet_,
                getParentForChildren(),
                isClean());
        packet_ = null;
      }
      packetCase_ = 4;
      onChanged();
      return disconnectBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket, art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacketOrBuilder> pingBuilder_;
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPingPacket ping = 5;</code>
     * @return Whether the ping field is set.
     */
    @java.lang.Override
    public boolean hasPing() {
      return packetCase_ == 5;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPingPacket ping = 5;</code>
     * @return The ping.
     */
    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket getPing() {
      if (pingBuilder_ == null) {
        if (packetCase_ == 5) {
          return (art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket) packet_;
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket.getDefaultInstance();
      } else {
        if (packetCase_ == 5) {
          return pingBuilder_.getMessage();
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPingPacket ping = 5;</code>
     */
    public Builder setPing(art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket value) {
      if (pingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packet_ = value;
        onChanged();
      } else {
        pingBuilder_.setMessage(value);
      }
      packetCase_ = 5;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPingPacket ping = 5;</code>
     */
    public Builder setPing(
        art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket.Builder builderForValue) {
      if (pingBuilder_ == null) {
        packet_ = builderForValue.build();
        onChanged();
      } else {
        pingBuilder_.setMessage(builderForValue.build());
      }
      packetCase_ = 5;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPingPacket ping = 5;</code>
     */
    public Builder mergePing(art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket value) {
      if (pingBuilder_ == null) {
        if (packetCase_ == 5 &&
            packet_ != art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket.getDefaultInstance()) {
          packet_ = art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket.newBuilder((art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket) packet_)
              .mergeFrom(value).buildPartial();
        } else {
          packet_ = value;
        }
        onChanged();
      } else {
        if (packetCase_ == 5) {
          pingBuilder_.mergeFrom(value);
        } else {
          pingBuilder_.setMessage(value);
        }
      }
      packetCase_ = 5;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPingPacket ping = 5;</code>
     */
    public Builder clearPing() {
      if (pingBuilder_ == null) {
        if (packetCase_ == 5) {
          packetCase_ = 0;
          packet_ = null;
          onChanged();
        }
      } else {
        if (packetCase_ == 5) {
          packetCase_ = 0;
          packet_ = null;
        }
        pingBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPingPacket ping = 5;</code>
     */
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket.Builder getPingBuilder() {
      return getPingFieldBuilder().getBuilder();
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPingPacket ping = 5;</code>
     */
    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacketOrBuilder getPingOrBuilder() {
      if ((packetCase_ == 5) && (pingBuilder_ != null)) {
        return pingBuilder_.getMessageOrBuilder();
      } else {
        if (packetCase_ == 5) {
          return (art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket) packet_;
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.C2SPingPacket ping = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket, art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacketOrBuilder> 
        getPingFieldBuilder() {
      if (pingBuilder_ == null) {
        if (!(packetCase_ == 5)) {
          packet_ = art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket.getDefaultInstance();
        }
        pingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket, art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacketOrBuilder>(
                (art.ameliah.laby.addons.cubepanion.core.proto.C2SPingPacket) packet_,
                getParentForChildren(),
                isClean());
        packet_ = null;
      }
      packetCase_ = 5;
      onChanged();
      return pingBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:art.ameliah.laby.addons.cubepanion.C2SPacket)
  }

  // @@protoc_insertion_point(class_scope:art.ameliah.laby.addons.cubepanion.C2SPacket)
  private static final art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket();
  }

  public static art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<C2SPacket>
      PARSER = new com.google.protobuf.AbstractParser<C2SPacket>() {
    @java.lang.Override
    public C2SPacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<C2SPacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<C2SPacket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public art.ameliah.laby.addons.cubepanion.core.proto.C2SPacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

