// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.3
package art.ameliah.laby.addons.cubepanion.core.proto;

public interface C2SPerkUpdatePacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.laby.addons.cubepanion.C2SPerkUpdatePacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.art.ameliah.laby.addons.cubepanion.PerkCategory category = 1;</code>
   * @return The enum numeric value on the wire for category.
   */
  int getCategoryValue();
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.PerkCategory category = 1;</code>
   * @return The category.
   */
  art.ameliah.laby.addons.cubepanion.core.proto.PerkCategory getCategory();

  /**
   * <code>repeated string perks = 2;</code>
   * @return A list containing the perks.
   */
  java.util.List<java.lang.String>
      getPerksList();
  /**
   * <code>repeated string perks = 2;</code>
   * @return The count of perks.
   */
  int getPerksCount();
  /**
   * <code>repeated string perks = 2;</code>
   * @param index The index of the element to return.
   * @return The perks at the given index.
   */
  java.lang.String getPerks(int index);
  /**
   * <code>repeated string perks = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the perks at the given index.
   */
  com.google.protobuf.ByteString
      getPerksBytes(int index);
}
