// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.3
package art.ameliah.laby.addons.cubepanion.core.proto;

public interface C2SUpdateLocationPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.laby.addons.cubepanion.C2SUpdateLocationPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string origin = 1;</code>
   * @return The origin.
   */
  java.lang.String getOrigin();
  /**
   * <code>string origin = 1;</code>
   * @return The bytes for origin.
   */
  com.google.protobuf.ByteString
      getOriginBytes();

  /**
   * <code>string destination = 2;</code>
   * @return The destination.
   */
  java.lang.String getDestination();
  /**
   * <code>string destination = 2;</code>
   * @return The bytes for destination.
   */
  com.google.protobuf.ByteString
      getDestinationBytes();

  /**
   * <code>bool preLobby = 3;</code>
   * @return The preLobby.
   */
  boolean getPreLobby();
}
