// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.3
package art.ameliah.laby.addons.cubepanion.core.proto;

/**
 * Protobuf enum {@code art.ameliah.laby.addons.cubepanion.PerkCategory}
 */
public enum PerkCategory
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PERSONAL = 0;</code>
   */
  PERSONAL(0),
  /**
   * <code>TEAM = 1;</code>
   */
  TEAM(1),
  /**
   * <code>GAME = 2;</code>
   */
  GAME(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PERSONAL = 0;</code>
   */
  public static final int PERSONAL_VALUE = 0;
  /**
   * <code>TEAM = 1;</code>
   */
  public static final int TEAM_VALUE = 1;
  /**
   * <code>GAME = 2;</code>
   */
  public static final int GAME_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PerkCategory valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PerkCategory forNumber(int value) {
    switch (value) {
      case 0: return PERSONAL;
      case 1: return TEAM;
      case 2: return GAME;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PerkCategory>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PerkCategory> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PerkCategory>() {
          public PerkCategory findValueByNumber(int number) {
            return PerkCategory.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return art.ameliah.laby.addons.cubepanion.core.proto.Packets.getDescriptor().getEnumTypes().get(0);
  }

  private static final PerkCategory[] VALUES = values();

  public static PerkCategory valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PerkCategory(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:art.ameliah.laby.addons.cubepanion.PerkCategory)
}

