// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.2
package art.ameliah.laby.addons.cubepanion.core.proto;

public interface S2CHelloPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.laby.addons.cubepanion.S2CHelloPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 time = 1;</code>
   * @return The time.
   */
  long getTime();
}
