// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.3
package art.ameliah.laby.addons.cubepanion.core.proto;

public interface S2CPingPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.laby.addons.cubepanion.S2CPingPacket)
    com.google.protobuf.MessageOrBuilder {
}
