// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.2
package art.ameliah.laby.addons.cubepanion.core.proto;

public interface S2CPacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:art.ameliah.laby.addons.cubepanion.S2CPacket)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
   * @return Whether the updatePerk field is set.
   */
  boolean hasUpdatePerk();
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
   * @return The updatePerk.
   */
  art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket getUpdatePerk();
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
   */
  art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacketOrBuilder getUpdatePerkOrBuilder();

  /**
   * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
   * @return Whether the hello field is set.
   */
  boolean hasHello();
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
   * @return The hello.
   */
  art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket getHello();
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
   */
  art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacketOrBuilder getHelloOrBuilder();

  art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket.PacketCase getPacketCase();
}
