// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packets.proto

// Protobuf Java Version: 3.25.2
package art.ameliah.laby.addons.cubepanion.core.proto;

/**
 * Protobuf type {@code art.ameliah.laby.addons.cubepanion.S2CPacket}
 */
public final class S2CPacket extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:art.ameliah.laby.addons.cubepanion.S2CPacket)
    S2CPacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use S2CPacket.newBuilder() to construct.
  private S2CPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private S2CPacket() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new S2CPacket();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return art.ameliah.laby.addons.cubepanion.core.proto.Packets.internal_static_art_ameliah_laby_addons_cubepanion_S2CPacket_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return art.ameliah.laby.addons.cubepanion.core.proto.Packets.internal_static_art_ameliah_laby_addons_cubepanion_S2CPacket_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket.class, art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket.Builder.class);
  }

  private int packetCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object packet_;
  public enum PacketCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    UPDATEPERK(1),
    HELLO(2),
    PACKET_NOT_SET(0);
    private final int value;
    private PacketCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PacketCase valueOf(int value) {
      return forNumber(value);
    }

    public static PacketCase forNumber(int value) {
      switch (value) {
        case 1: return UPDATEPERK;
        case 2: return HELLO;
        case 0: return PACKET_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PacketCase
  getPacketCase() {
    return PacketCase.forNumber(
        packetCase_);
  }

  public static final int UPDATEPERK_FIELD_NUMBER = 1;
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
   * @return Whether the updatePerk field is set.
   */
  @java.lang.Override
  public boolean hasUpdatePerk() {
    return packetCase_ == 1;
  }
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
   * @return The updatePerk.
   */
  @java.lang.Override
  public art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket getUpdatePerk() {
    if (packetCase_ == 1) {
       return (art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket) packet_;
    }
    return art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket.getDefaultInstance();
  }
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
   */
  @java.lang.Override
  public art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacketOrBuilder getUpdatePerkOrBuilder() {
    if (packetCase_ == 1) {
       return (art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket) packet_;
    }
    return art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket.getDefaultInstance();
  }

  public static final int HELLO_FIELD_NUMBER = 2;
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
   * @return Whether the hello field is set.
   */
  @java.lang.Override
  public boolean hasHello() {
    return packetCase_ == 2;
  }
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
   * @return The hello.
   */
  @java.lang.Override
  public art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket getHello() {
    if (packetCase_ == 2) {
       return (art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket) packet_;
    }
    return art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket.getDefaultInstance();
  }
  /**
   * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
   */
  @java.lang.Override
  public art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacketOrBuilder getHelloOrBuilder() {
    if (packetCase_ == 2) {
       return (art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket) packet_;
    }
    return art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (packetCase_ == 1) {
      output.writeMessage(1, (art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket) packet_);
    }
    if (packetCase_ == 2) {
      output.writeMessage(2, (art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket) packet_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (packetCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket) packet_);
    }
    if (packetCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket) packet_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket)) {
      return super.equals(obj);
    }
    art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket other = (art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket) obj;

    if (!getPacketCase().equals(other.getPacketCase())) return false;
    switch (packetCase_) {
      case 1:
        if (!getUpdatePerk()
            .equals(other.getUpdatePerk())) return false;
        break;
      case 2:
        if (!getHello()
            .equals(other.getHello())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (packetCase_) {
      case 1:
        hash = (37 * hash) + UPDATEPERK_FIELD_NUMBER;
        hash = (53 * hash) + getUpdatePerk().hashCode();
        break;
      case 2:
        hash = (37 * hash) + HELLO_FIELD_NUMBER;
        hash = (53 * hash) + getHello().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code art.ameliah.laby.addons.cubepanion.S2CPacket}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:art.ameliah.laby.addons.cubepanion.S2CPacket)
      art.ameliah.laby.addons.cubepanion.core.proto.S2CPacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return art.ameliah.laby.addons.cubepanion.core.proto.Packets.internal_static_art_ameliah_laby_addons_cubepanion_S2CPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return art.ameliah.laby.addons.cubepanion.core.proto.Packets.internal_static_art_ameliah_laby_addons_cubepanion_S2CPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket.class, art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket.Builder.class);
    }

    // Construct using art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (updatePerkBuilder_ != null) {
        updatePerkBuilder_.clear();
      }
      if (helloBuilder_ != null) {
        helloBuilder_.clear();
      }
      packetCase_ = 0;
      packet_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return art.ameliah.laby.addons.cubepanion.core.proto.Packets.internal_static_art_ameliah_laby_addons_cubepanion_S2CPacket_descriptor;
    }

    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket getDefaultInstanceForType() {
      return art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket.getDefaultInstance();
    }

    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket build() {
      art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket buildPartial() {
      art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket result = new art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket result) {
      result.packetCase_ = packetCase_;
      result.packet_ = this.packet_;
      if (packetCase_ == 1 &&
          updatePerkBuilder_ != null) {
        result.packet_ = updatePerkBuilder_.build();
      }
      if (packetCase_ == 2 &&
          helloBuilder_ != null) {
        result.packet_ = helloBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket) {
        return mergeFrom((art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket other) {
      if (other == art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket.getDefaultInstance()) return this;
      switch (other.getPacketCase()) {
        case UPDATEPERK: {
          mergeUpdatePerk(other.getUpdatePerk());
          break;
        }
        case HELLO: {
          mergeHello(other.getHello());
          break;
        }
        case PACKET_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getUpdatePerkFieldBuilder().getBuilder(),
                  extensionRegistry);
              packetCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getHelloFieldBuilder().getBuilder(),
                  extensionRegistry);
              packetCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int packetCase_ = 0;
    private java.lang.Object packet_;
    public PacketCase
        getPacketCase() {
      return PacketCase.forNumber(
          packetCase_);
    }

    public Builder clearPacket() {
      packetCase_ = 0;
      packet_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket, art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacketOrBuilder> updatePerkBuilder_;
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
     * @return Whether the updatePerk field is set.
     */
    @java.lang.Override
    public boolean hasUpdatePerk() {
      return packetCase_ == 1;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
     * @return The updatePerk.
     */
    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket getUpdatePerk() {
      if (updatePerkBuilder_ == null) {
        if (packetCase_ == 1) {
          return (art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket) packet_;
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket.getDefaultInstance();
      } else {
        if (packetCase_ == 1) {
          return updatePerkBuilder_.getMessage();
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
     */
    public Builder setUpdatePerk(art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket value) {
      if (updatePerkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packet_ = value;
        onChanged();
      } else {
        updatePerkBuilder_.setMessage(value);
      }
      packetCase_ = 1;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
     */
    public Builder setUpdatePerk(
        art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket.Builder builderForValue) {
      if (updatePerkBuilder_ == null) {
        packet_ = builderForValue.build();
        onChanged();
      } else {
        updatePerkBuilder_.setMessage(builderForValue.build());
      }
      packetCase_ = 1;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
     */
    public Builder mergeUpdatePerk(art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket value) {
      if (updatePerkBuilder_ == null) {
        if (packetCase_ == 1 &&
            packet_ != art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket.getDefaultInstance()) {
          packet_ = art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket.newBuilder((art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket) packet_)
              .mergeFrom(value).buildPartial();
        } else {
          packet_ = value;
        }
        onChanged();
      } else {
        if (packetCase_ == 1) {
          updatePerkBuilder_.mergeFrom(value);
        } else {
          updatePerkBuilder_.setMessage(value);
        }
      }
      packetCase_ = 1;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
     */
    public Builder clearUpdatePerk() {
      if (updatePerkBuilder_ == null) {
        if (packetCase_ == 1) {
          packetCase_ = 0;
          packet_ = null;
          onChanged();
        }
      } else {
        if (packetCase_ == 1) {
          packetCase_ = 0;
          packet_ = null;
        }
        updatePerkBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
     */
    public art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket.Builder getUpdatePerkBuilder() {
      return getUpdatePerkFieldBuilder().getBuilder();
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
     */
    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacketOrBuilder getUpdatePerkOrBuilder() {
      if ((packetCase_ == 1) && (updatePerkBuilder_ != null)) {
        return updatePerkBuilder_.getMessageOrBuilder();
      } else {
        if (packetCase_ == 1) {
          return (art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket) packet_;
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CPerkUpdatePacket updatePerk = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket, art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacketOrBuilder> 
        getUpdatePerkFieldBuilder() {
      if (updatePerkBuilder_ == null) {
        if (!(packetCase_ == 1)) {
          packet_ = art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket.getDefaultInstance();
        }
        updatePerkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket, art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacketOrBuilder>(
                (art.ameliah.laby.addons.cubepanion.core.proto.S2CPerkUpdatePacket) packet_,
                getParentForChildren(),
                isClean());
        packet_ = null;
      }
      packetCase_ = 1;
      onChanged();
      return updatePerkBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket, art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacketOrBuilder> helloBuilder_;
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
     * @return Whether the hello field is set.
     */
    @java.lang.Override
    public boolean hasHello() {
      return packetCase_ == 2;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
     * @return The hello.
     */
    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket getHello() {
      if (helloBuilder_ == null) {
        if (packetCase_ == 2) {
          return (art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket) packet_;
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket.getDefaultInstance();
      } else {
        if (packetCase_ == 2) {
          return helloBuilder_.getMessage();
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
     */
    public Builder setHello(art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket value) {
      if (helloBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packet_ = value;
        onChanged();
      } else {
        helloBuilder_.setMessage(value);
      }
      packetCase_ = 2;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
     */
    public Builder setHello(
        art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket.Builder builderForValue) {
      if (helloBuilder_ == null) {
        packet_ = builderForValue.build();
        onChanged();
      } else {
        helloBuilder_.setMessage(builderForValue.build());
      }
      packetCase_ = 2;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
     */
    public Builder mergeHello(art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket value) {
      if (helloBuilder_ == null) {
        if (packetCase_ == 2 &&
            packet_ != art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket.getDefaultInstance()) {
          packet_ = art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket.newBuilder((art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket) packet_)
              .mergeFrom(value).buildPartial();
        } else {
          packet_ = value;
        }
        onChanged();
      } else {
        if (packetCase_ == 2) {
          helloBuilder_.mergeFrom(value);
        } else {
          helloBuilder_.setMessage(value);
        }
      }
      packetCase_ = 2;
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
     */
    public Builder clearHello() {
      if (helloBuilder_ == null) {
        if (packetCase_ == 2) {
          packetCase_ = 0;
          packet_ = null;
          onChanged();
        }
      } else {
        if (packetCase_ == 2) {
          packetCase_ = 0;
          packet_ = null;
        }
        helloBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
     */
    public art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket.Builder getHelloBuilder() {
      return getHelloFieldBuilder().getBuilder();
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
     */
    @java.lang.Override
    public art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacketOrBuilder getHelloOrBuilder() {
      if ((packetCase_ == 2) && (helloBuilder_ != null)) {
        return helloBuilder_.getMessageOrBuilder();
      } else {
        if (packetCase_ == 2) {
          return (art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket) packet_;
        }
        return art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket.getDefaultInstance();
      }
    }
    /**
     * <code>.art.ameliah.laby.addons.cubepanion.S2CHelloPacket hello = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket, art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacketOrBuilder> 
        getHelloFieldBuilder() {
      if (helloBuilder_ == null) {
        if (!(packetCase_ == 2)) {
          packet_ = art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket.getDefaultInstance();
        }
        helloBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket, art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket.Builder, art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacketOrBuilder>(
                (art.ameliah.laby.addons.cubepanion.core.proto.S2CHelloPacket) packet_,
                getParentForChildren(),
                isClean());
        packet_ = null;
      }
      packetCase_ = 2;
      onChanged();
      return helloBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:art.ameliah.laby.addons.cubepanion.S2CPacket)
  }

  // @@protoc_insertion_point(class_scope:art.ameliah.laby.addons.cubepanion.S2CPacket)
  private static final art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket();
  }

  public static art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<S2CPacket>
      PARSER = new com.google.protobuf.AbstractParser<S2CPacket>() {
    @java.lang.Override
    public S2CPacket parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<S2CPacket> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<S2CPacket> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public art.ameliah.laby.addons.cubepanion.core.proto.S2CPacket getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

